#
# Base configuration
#

baseURL      = 'http://example.org/'
title        = 'Instituto de Computação / UFRJ'
languageCode = 'pt-br'

theme = 'arcana'
defaultContentLanguage = 'pt-br'
pluralizelisttitles = "false"

#
# Menu hierarchy
#

[[menus.main]]
    weight  = 1
    name    = 'Home'
    pageRef = '/'

[[menus.main]]
    weight  = 2
    name    = 'Instituto'
    pageRef = '/instituto'

    [[menus.main]]
        parent  = 'Instituto'
        name    = 'Pessoas'
        pageRef = '/instituto/pessoas'

    [[menus.main]]
        parent  = 'Instituto'
        name    = 'Contato'
        pageRef = '/instituto/contato'

    [[menus.main]]
        parent  = 'Instituto'
        name    = 'Localização'
        pageRef = '/instituto/localizacao'

[[menus.main]]
    weight  = 3
    name    = 'Ensino'
    pageRef = '/ensino'

[[menus.main]]
    weight  = 4
    name    = 'Pesquisa'
    pageRef = '/pesquisa'

[[menus.main]]
    weight  = 5
    name    = 'Extensão'
    pageRef = '/extensao'

[[menus.main]]
    weight  = 6
    name    = 'Alunos'
    pageref = '/alunos'

#
# Template & Theme configuration
#

[params]
    # todo

